server:
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /public/**
  resources:
    static-locations: classpath:/static
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/streamtau2?useSSL=false'
    username: test
    password:
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/changelog-master.yml'
  thymeleaf:
    enabled: true
    check-template: true
    check-template-location: true
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: true
    prefix: classpath:/view/
mybatis:
  config-location: 'classpath:/db/mybatis-config.xml'
streamtau:
  storage:
    type: local
    local:
      dir: ~
  streaming:
    lib-path: lib/
