server:
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: 'jdbc:h2:mem:test'
    username: test
    password:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/changelog-master.yml'
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
mybatis:
  config-location: 'classpath:/db/mybatis-config.xml'
springdoc:
  packagesToScan: 'com.zetyun.streamtau.manager.controller'
  swagger-ui:
    enabled: true
streamtau:
  storage:
    type: local
    local:
      dir: ~
  streaming:
    lib-path: ${streaming.lib-path}
